export const types0 = {
  'INCREMENT': 'INCREMENT',
  'DECREMENT': 'DECREMENT',
  'SET_COUNT': 'SET_COUNT'
}

export const types1 = {
  'INCREMENT': 'INCREMENT' as 'INCREMENT',
  'DECREMENT': 'DECREMENT' as 'DECREMENT',
  'SET_COUNT': 'SET_COUNT' as 'SET_COUNT'
}

export const types2 = {
  'INCREMENT': 'COUNTER_INCREMENT' as 'COUNTER_INCREMENT',
  'DECREMENT': 'COUNTER_DECREMENT' as 'COUNTER_DECREMENT',
  'SET_COUNT': 'COUNTER_SET_COUNT' as 'COUNTER_SET_COUNT'
}

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const SET_COUNT = 'SET_COUNT'

export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'
export const COUNTER_SET_COUNT = 'COUNTER_SET_COUNT'
